# Generated by Django 4.1.13 on 2023-12-16 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_user', models.FileField(blank=True, null=True, upload_to='profile/uploaded_files/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='routine',
            name='no_of_period_value',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='routine',
            name='season',
            field=models.CharField(choices=[('winter', 'Winter'), ('summer', 'Summer')], default='summer', max_length=10),
        ),
        migrations.AddField(
            model_name='routine',
            name='starting_period_value',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='post',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RemoveField(
            model_name='routine',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='routine',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AddField(
            model_name='routine',
            name='teacher',
            field=models.ManyToManyField(to='api.teacher'),
        ),
    ]
