# Generated by Django 4.2.3 on 2023-07-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_semester_teacher_alter_student_roll_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
