# Generated by Django 4.2.4 on 2023-12-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_routine_teacher_routine_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
