# Generated by Django 4.2.4 on 2023-12-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_subject_semester_remove_subject_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='teacher',
            field=models.ManyToManyField(null=True, to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
