# Generated by Django 4.2.4 on 2023-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_routine_teacher_alter_routine_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
