# Generated by Django 4.2.4 on 2023-12-11 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_routine_time_end_alter_routine_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='teacher',
            field=models.ManyToManyField(to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='time_end',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routine',
            name='time_start',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
