# Generated by Django 4.2.3 on 2023-07-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teacher_subject_alter_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.semester'),
            preserve_default=False,
        ),
    ]
