# Generated by Django 4.2.4 on 2023-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_teacher_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='no_of_period_value',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='routine',
            name='season',
            field=models.CharField(choices=[('winter', 'Winter'), ('summer', 'Summer')], default='summer', max_length=10),
        ),
        migrations.AddField(
            model_name='routine',
            name='starting_period_value',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
