# Generated by Django 4.2.3 on 2023-07-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_semester_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ManyToManyField(to='api.subject')),
                ('year', models.ManyToManyField(to='api.year')),
            ],
        ),
    ]
