# Generated by Django 4.2.4 on 2023-12-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_routine_no_of_period_value_routine_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='time_end',
            field=models.TimeField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='routine',
            name='time_start',
            field=models.TimeField(blank=True, max_length=10),
        ),
    ]
