# Generated by Django 4.2.4 on 2023-12-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_routine_time_end_alter_routine_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='time_end',
            field=models.TimeField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='time_start',
            field=models.TimeField(blank=True, max_length=10, null=True),
        ),
    ]
