# Generated by Django 4.2.3 on 2023-07-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_subject_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
    ]
