# Generated by Django 4.2.3 on 2023-08-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_subject_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='type',
            new_name='attendance_status',
        ),
    ]
