# Generated by Django 4.2.3 on 2023-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3),
        ),
    ]
