# Generated by Django 4.2.4 on 2023-12-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_subject_year_routine_year_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
