# Generated by Django 4.2.4 on 2023-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_routine_section_alter_routine_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='api.teacher'),
        ),
    ]
