# Generated by Django 4.1.13 on 2024-01-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_teacher_email_alter_teacher_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='post',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
