# Generated by Django 5.0.6 on 2024-05-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_routine_alternate_bool"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="shift",
            field=models.CharField(
                choices=[("morning", "Morning"), ("day", "Day")],
                default="day",
                max_length=10,
            ),
        ),
    ]
